/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SJoe68ZkRIS
 */
import { CardTitle, CardContent, Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

export function Component() {
	return (
		<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
			<Card className="transform transition-transform duration-500 hover:scale-105 hover:shadow-lg">
				<CardContent className="flex flex-col items-center space-y-4 p-4">
					<img
						alt="Placeholder"
						className="w-full rounded-lg object-cover"
						height="200"
						src="/textract_appsync.png"
						style={{
							aspectRatio: '300/200',
							objectFit: 'cover',
						}}
						width="300"
					/>
					<CardTitle className="text-lg font-bold">Expense Reporter</CardTitle>
					<Button variant="default">
						<a href="https://github.com/focusOtter/textract-expense-tracker">
							Click Me
						</a>
					</Button>
				</CardContent>
			</Card>
			<Card className="transform transition-transform duration-500 hover:scale-105 hover:shadow-lg">
				<CardContent className="flex flex-col items-center space-y-4 p-4">
					<img
						alt="Placeholder"
						className="w-full rounded-lg object-cover"
						height="200"
						src="/appsync-bedrock.png"
						style={{
							aspectRatio: '300/200',
							objectFit: 'cover',
						}}
						width="300"
					/>
					<CardTitle className="text-lg font-bold">AppSync + Bedrock</CardTitle>
					<Button variant="default">
						<a href="https://github.com/focusOtter/sample-wordsearch/tree/main">
							Click Me
						</a>
					</Button>
				</CardContent>
			</Card>
			<Card className="transform transition-transform duration-500 hover:scale-105 hover:shadow-lg">
				<CardContent className="flex flex-col items-center space-y-4 p-4">
					<img
						alt="Placeholder"
						className="w-full rounded-lg object-cover"
						height="200"
						src="/chat-app-translate.png"
						style={{
							aspectRatio: '300/200',
							objectFit: 'cover',
						}}
						width="300"
					/>
					<CardTitle className="text-lg font-bold">
						Realtime Events Chat
					</CardTitle>
					<Button variant="default">
						<a href="https://github.com/focusOtter/appsync-chat-translate">
							Click Me
						</a>
					</Button>
				</CardContent>
			</Card>
		</div>
	)
}
